{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "be3ba57d",
        "outputId": "f753f65f-098b-4da9-fee4-30d50faee14a"
      },
      "source": [
        "!pip install streamlit"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.53.0-py3-none-any.whl.metadata (10 kB)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.4)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)\n",
            "Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.2)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.15.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.1.4)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.53.0-py3-none-any.whl (9.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.1/9.1 MB\u001b[0m \u001b[31m91.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m108.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.53.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bc9721fd",
        "outputId": "a5b510fb-7fdb-475b-9d09-e9dee86e9087"
      },
      "source": [
        "import sys\n",
        "import os\n",
        "\n",
        "# Add the current directory to the Python path to allow importing from 'src'\n",
        "sys.path.append(os.getcwd())\n",
        "print(f\"Current working directory added to sys.path: {os.getcwd()}\")"
      ],
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Current working directory added to sys.path: /content\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yZRtdxIOKXq3",
        "outputId": "020bffa6-156e-40b2-ab5f-924e6b0fc936"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Streamlit app code saved to app.py\n"
          ]
        }
      ],
      "source": [
        "app_code = '''\n",
        "\"\"\"\n",
        "AI Travel Planner - Main Application\n",
        "A comprehensive travel planning app powered by AI agents.\n",
        "\"\"\"\n",
        "\n",
        "import streamlit as st\n",
        "from datetime import date, timedelta\n",
        "\n",
        "# Import configurations\n",
        "from src.config.settings import settings\n",
        "\n",
        "# Import services\n",
        "from src.services.flight_service import FlightService\n",
        "\n",
        "# Import agents\n",
        "from src.agents.researcher import ResearchAgent\n",
        "from src.agents.planner import PlannerAgent\n",
        "from src.agents.finder import FinderAgent\n",
        "\n",
        "# Import UI components\n",
        "from src.ui.styles import get_custom_css, get_welcome_banner\n",
        "from src.ui.sidebar import render_sidebar\n",
        "from src.ui.components import (\n",
        "    render_flight_card,\n",
        "    render_section_header,\n",
        "    render_info_box\n",
        ")\n",
        "\n",
        "# Import utilities\n",
        "from src.utils.validators import (\n",
        "    validate_iata_code,\n",
        "    validate_dates,\n",
        "    validate_activity_preferences\n",
        ")\n",
        "\n",
        "\n",
        "def initialize_app():\n",
        "    \"\"\"Initialize the Streamlit app with configuration\"\"\"\n",
        "    st.set_page_config(\n",
        "        page_title=settings.PAGE_TITLE,\n",
        "        layout=settings.PAGE_LAYOUT,\n",
        "        initial_sidebar_state=\"expanded\"\n",
        "    )\n",
        "\n",
        "    # Apply custom CSS\n",
        "    st.markdown(get_custom_css(), unsafe_allow_html=True)\n",
        "\n",
        "    # Validate API keys\n",
        "    if not settings.validate_keys():\n",
        "        st.stop()\n",
        "\n",
        "\n",
        "def render_header():\n",
        "    \"\"\"Render the application header\"\"\"\n",
        "    st.markdown(\n",
        "        '<h1 class=\"title\">✈️ AI-Powered Travel Planner</h1>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "    st.markdown(\n",
        "        '<p class=\"subtitle\">Plan your dream trip with AI! Get personalized recommendations for flights, hotels, and activities.</p>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "\n",
        "def get_user_inputs():\n",
        "    \"\"\"\n",
        "    Get and validate user inputs from the main form.\n",
        "\n",
        "    Returns:\n",
        "        Dictionary containing all user inputs\n",
        "    \"\"\"\n",
        "    # Location inputs\n",
        "    st.markdown(\"### 🌍 Where are you headed?\")\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        source = st.text_input(\n",
        "            \"🛫 Departure City (IATA Code):\",\n",
        "            value=settings.DEFAULT_SOURCE,\n",
        "            max_chars=3,\n",
        "            help=\"Enter 3-letter airport code (e.g., BOM for Mumbai)\"\n",
        "        ).upper()\n",
        "\n",
        "    with col2:\n",
        "        destination = st.text_input(\n",
        "            \"🛬 Destination (IATA Code):\",\n",
        "            value=settings.DEFAULT_DESTINATION,\n",
        "            max_chars=3,\n",
        "            help=\"Enter 3-letter airport code (e.g., DEL for Delhi)\"\n",
        "        ).upper()\n",
        "\n",
        "    # Trip details\n",
        "    st.markdown(\"### 📅 Plan Your Adventure\")\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        num_days = st.slider(\n",
        "            \"🕒 Trip Duration (days):\",\n",
        "            min_value=settings.MIN_TRIP_DAYS,\n",
        "            max_value=settings.MAX_TRIP_DAYS,\n",
        "            value=settings.DEFAULT_TRIP_DURATION\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "        travel_theme = st.selectbox(\n",
        "            \"🎭 Select Your Travel Theme:\",\n",
        "            settings.TRAVEL_THEMES\n",
        "        )\n",
        "\n",
        "    # Date selection\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        departure_date = st.date_input(\n",
        "            \"📅 Departure Date\",\n",
        "            value=date.today() + timedelta(days=7),\n",
        "            min_value=date.today()\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "        return_date = st.date_input(\n",
        "            \"📅 Return Date\",\n",
        "            value=date.today() + timedelta(days=7 + num_days),\n",
        "            min_value=departure_date\n",
        "        )\n",
        "\n",
        "    # Activity preferences\n",
        "    activity_preferences = st.text_area(\n",
        "        \"🌍 What activities do you enjoy?\",\n",
        "        value=\"Relaxing on the beach, exploring historical sites, trying local cuisine\",\n",
        "        help=\"Describe your interests and preferred activities\",\n",
        "        height=100\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"source\": source,\n",
        "        \"destination\": destination,\n",
        "        \"num_days\": num_days,\n",
        "        \"travel_theme\": travel_theme,\n",
        "        \"departure_date\": departure_date,\n",
        "        \"return_date\": return_date,\n",
        "        \"activity_preferences\": activity_preferences\n",
        "    }\n",
        "\n",
        "\n",
        "def validate_inputs(inputs, sidebar_data):\n",
        "    \"\"\"\n",
        "    Validate all user inputs.\n",
        "\n",
        "    Args:\n",
        "        inputs: User inputs dictionary\n",
        "        sidebar_data: Sidebar selections dictionary\n",
        "\n",
        "    Returns:\n",
        "        tuple: (is_valid, error_messages)\n",
        "    \"\"\"\n",
        "    errors = []\n",
        "\n",
        "    # Validate source airport\n",
        "    is_valid, error = validate_iata_code(inputs[\"source\"])\n",
        "    if not is_valid:\n",
        "        errors.append(f\"Departure: {error}\")\n",
        "\n",
        "    # Validate destination airport\n",
        "    is_valid, error = validate_iata_code(inputs[\"destination\"])\n",
        "    if not is_valid:\n",
        "        errors.append(f\"Destination: {error}\")\n",
        "\n",
        "    # Check if source and destination are different\n",
        "    if inputs[\"source\"] == inputs[\"destination\"]:\n",
        "        errors.append(\"Departure and destination must be different\")\n",
        "\n",
        "    # Validate dates\n",
        "    is_valid, error = validate_dates(inputs[\"departure_date\"], inputs[\"return_date\"])\n",
        "    if not is_valid:\n",
        "        errors.append(error)\n",
        "\n",
        "    # Validate activity preferences\n",
        "    is_valid, error = validate_activity_preferences(inputs[\"activity_preferences\"])\n",
        "    if not is_valid:\n",
        "        errors.append(error)\n",
        "\n",
        "    return len(errors) == 0, errors\n",
        "\n",
        "\n",
        "def main():\n",
        "    \"\"\"Main application logic\"\"\"\n",
        "\n",
        "    # Initialize app\n",
        "    initialize_app()\n",
        "\n",
        "    # Render header\n",
        "    render_header()\n",
        "\n",
        "    # Get sidebar inputs\n",
        "    sidebar_data = render_sidebar()\n",
        "\n",
        "    # Get main form inputs\n",
        "    user_inputs = get_user_inputs()\n",
        "\n",
        "    # Display welcome banner\n",
        "    st.markdown(\"---\")\n",
        "    st.markdown(\n",
        "        get_welcome_banner(\n",
        "            user_inputs[\"travel_theme\"],\n",
        "            user_inputs[\"destination\"]\n",
        "        ),\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "    # Generate travel plan button\n",
        "    if st.button(\"🚀 Generate Travel Plan\", type=\"primary\", use_container_width=True):\n",
        "\n",
        "        # Validate inputs\n",
        "        is_valid, errors = validate_inputs(user_inputs, sidebar_data)\n",
        "\n",
        "        if not is_valid:\n",
        "            for error in errors:\n",
        "                st.error(f\"❌ {error}\")\n",
        "            st.stop()\n",
        "\n",
        "        # Initialize services and agents with different models\n",
        "        flight_service = FlightService(settings.SERPAPI_KEY)\n",
        "        researcher = ResearchAgent(settings.GEMINI_MODEL_RESEARCH, settings.SERPAPI_KEY)\n",
        "        finder = FinderAgent(settings.GEMINI_MODEL_FINDER, settings.SERPAPI_KEY)\n",
        "        planner = PlannerAgent(settings.GEMINI_MODEL_PLANNER)\n",
        "\n",
        "        # Step 1: Search for flights\n",
        "        with st.spinner(\"✈️ Searching for best flight options...\"):\n",
        "            flights = flight_service.search_and_extract(\n",
        "                source=user_inputs[\"source\"],\n",
        "                destination=user_inputs[\"destination\"],\n",
        "                departure_date=str(user_inputs[\"departure_date\"]),\n",
        "                return_date=str(user_inputs[\"return_date\"]),\n",
        "                limit=3\n",
        "            )\n",
        "\n",
        "        # Step 2: Research destination\n",
        "        with st.spinner(\"🔍 Researching destination attractions & activities...\"):\n",
        "            research_results = researcher.research_destination(\n",
        "                destination=user_inputs[\"destination\"],\n",
        "                num_days=user_inputs[\"num_days\"],\n",
        "                travel_theme=user_inputs[\"travel_theme\"],\n",
        "                activity_preferences=user_inputs[\"activity_preferences\"],\n",
        "                budget=sidebar_data[\"budget\"]\n",
        "            )\n",
        "\n",
        "        # Step 3: Find hotels and restaurants\n",
        "        with st.spinner(\"🏨 Finding best hotels & restaurants...\"):\n",
        "            hotel_restaurant_results = finder.find_accommodations(\n",
        "                destination=user_inputs[\"destination\"],\n",
        "                travel_theme=user_inputs[\"travel_theme\"],\n",
        "                budget=sidebar_data[\"budget\"],\n",
        "                hotel_rating=sidebar_data[\"hotel_rating\"],\n",
        "                activity_preferences=user_inputs[\"activity_preferences\"]\n",
        "            )\n",
        "\n",
        "        # Step 4: Create itinerary\n",
        "        with st.spinner(\"🗺️ Creating your personalized itinerary...\"):\n",
        "            itinerary = planner.create_itinerary(\n",
        "                destination=user_inputs[\"destination\"],\n",
        "                num_days=user_inputs[\"num_days\"],\n",
        "                travel_theme=user_inputs[\"travel_theme\"],\n",
        "                activity_preferences=user_inputs[\"activity_preferences\"],\n",
        "                budget=sidebar_data[\"budget\"],\n",
        "                research_data=research_results,\n",
        "                hotel_data=hotel_restaurant_results\n",
        "            )\n",
        "\n",
        "        # Display Results\n",
        "        st.markdown(\"---\")\n",
        "\n",
        "        # Flight Results\n",
        "        render_section_header(\"Cheapest Flight Options\", \"✈️\")\n",
        "\n",
        "        if flights:\n",
        "            cols = st.columns(len(flights))\n",
        "            for idx, flight in enumerate(flights):\n",
        "                with cols[idx]:\n",
        "                    # Try to get booking link\n",
        "                    booking_link = \"#\"\n",
        "                    try:\n",
        "                        if flight.get(\"departure_token\"):\n",
        "                            booking_link = flight_service.get_booking_link(\n",
        "                                flight,\n",
        "                                user_inputs[\"source\"],\n",
        "                                user_inputs[\"destination\"],\n",
        "                                str(user_inputs[\"departure_date\"]),\n",
        "                                str(user_inputs[\"return_date\"])\n",
        "                            )\n",
        "                    except Exception as e:\n",
        "                        st.warning(f\"Booking link unavailable: {str(e)}\")\n",
        "\n",
        "                    render_flight_card(flight, booking_link)\n",
        "        else:\n",
        "            render_info_box(\n",
        "                \"⚠️ No flights found for the selected dates. Please try different dates.\",\n",
        "                \"warning\"\n",
        "            )\n",
        "\n",
        "        # Research Results\n",
        "        render_section_header(\"Destination Research\", \"🔍\")\n",
        "        st.markdown(research_results)\n",
        "\n",
        "        # Hotels & Restaurants\n",
        "        render_section_header(\"Hotels & Restaurants\", \"🏨\")\n",
        "        st.markdown(hotel_restaurant_results)\n",
        "\n",
        "        # Itinerary\n",
        "        render_section_header(\"Your Personalized Itinerary\", \"🗺️\")\n",
        "        st.markdown(itinerary)\n",
        "\n",
        "        # Success message\n",
        "        st.markdown(\"---\")\n",
        "        render_info_box(\n",
        "            \"✅ <strong>Travel plan generated successfully!</strong><br>\"\n",
        "            \"You can now save or share this itinerary. Have a wonderful trip! 🎉\",\n",
        "            \"success\"\n",
        "        )\n",
        "\n",
        "        # Download button for itinerary\n",
        "        full_plan = f\"\"\"\n",
        "# Travel Plan: {user_inputs['source']} to {user_inputs['destination']}\n",
        "\n",
        "## Trip Details\n",
        "- Duration: {user_inputs['num_days']} days\n",
        "- Theme: {user_inputs['travel_theme']}\n",
        "- Dates: {user_inputs['departure_date']} to {user_inputs['return_date']}\n",
        "\n",
        "## Flights\n",
        "{len(flights)} options found\n",
        "\n",
        "## Destination Research\n",
        "{research_results}\n",
        "\n",
        "## Hotels & Restaurants\n",
        "{hotel_restaurant_results}\n",
        "\n",
        "## Itinerary\n",
        "{itinerary}\n",
        "\"\"\"\n",
        "\n",
        "        st.download_button(\n",
        "            label=\"📥 Download Complete Travel Plan\",\n",
        "            data=full_plan,\n",
        "            file_name=f\"travel_plan_{user_inputs['destination']}.txt\",\n",
        "            mime=\"text/plain\"\n",
        "        )\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n",
        "'''\n",
        "\n",
        "with open('app.py', 'w') as f:\n",
        "    f.write(app_code)\n",
        "\n",
        "print(\"Streamlit app code saved to app.py\")\n"
      ]
    }
  ]
}